### ISSUE TITLE
Wrong file in notebook 055

### ISSUE THREAD

**Issue by rguilcas** [chrisroadmap/ar6#35]
Hi, 

In the notebook 055, the file **Smith_et_al_ACP_2020/aprp_aer_20200211.csv** is open but does not exist in the data-input directory. Instead, there is another different file **aprp_aer.csv** without the date at the end. These two files seem different when comparing the printed dataframe in your notebook and the dataframe when loading the latter file.

**Comment by chrisroadmap** [comment]
looks like an old version of this file/notebook got caught up here. The chapter 7 has more models. Will add correct input data in

**Comment by chrisroadmap** [comment]
fixed by #39.
