### ISSUE TITLE
Missing "data_input_large" directory in notebook 030

### ISSUE THREAD

**Issue by rguilcas** [chrisroadmap/ar6#36]
Hi,

In notebook 030, the first check_and_download fails as it checks in the **data_input_large** directory that does not exist yet.

check_and_download(
    '../data_input_large/rcmip-emissions-annual-means-v5-1-0.csv',
    'https://rcmip-protocols-au.s3-ap-southeast-2.amazonaws.com/v5.1.0/rcmip-emissions-annual-means-v5-1-0.csv'
)

**Comment by chrisroadmap** [comment]
ok, as a temporary thing you can simply make this directory by hand, just needs a mkdir_p in the cell before

**Comment by rguilcas** [comment]
> 

Yes, that's what I did. I just mentioned it in case anyone else needed it.

**Comment by chrisroadmap** [comment]
fixed in #38
