### ISSUE TITLE
Notebook 335 generate_metrics - d and q thermal parameters

### ISSUE THREAD

**Issue by cyrillefrancois** [chrisroadmap/ar6#50]
Hello,
In your notebook, why do you use others parameters than FaiR ? (e.g. d2=285 instead of 239 years)
You mention Zeb or Bill, but is there any paper to support these figures ? I'm very interested.
These parameters have quite significant impacts on AGTP (for CH4 I found 18% more temperature change with FaiR (1.6.2) parameters after 100 years)
Thanks for your clarification,
Cyrille

**Comment by chrisroadmap** [comment]
d=239 years is a CMIP5 calibration, and d=285 is a mean of fair and an impulse-response approximation of MAGICC trained on CMIP6 models. There's no paper - never any time to do those 👍 but if it's explained anywhere, which it probably isn't, it would be in chapter 7 SM.

PS metrics are terrible anyway - if you can run fair and adjust your emissions to get a climate effect, I would recommend this approach 11 times out of 10.

**Comment by cyrillefrancois** [comment]
Thanks for the answer, (I think you can close this issue)
In our field of research, Life Cycle Assessment, we based our results on characterization factors that are extracted from this metrics. 
For GWP, 20, 100 and 500 years are basic, but we open discussion on others horizons, this is why we recalculate these metrics for each time horizon from 0 to 1000. 
Uncertainties on metrics are well explained in the report and significant, but in LCA these metrics are centrals and never discuss.
